.MODEL SMALL
.STACK 100H
.DATA
	MSG DB "Enter a string (max 14 char) : $"
	STRING DB 14,0,16 DUP ("$")
	;COLOR_ATTR DB 0CH ;RED COLOR

.CODE
START:
	MOV AX, @DATA
	MOV DS, AX

	MOV AL, 03H
	MOV AH, 00H
	INT 10H ;VIDEO MODE TO 80X25 TEXT MODE
	
	LEA DX, MSG
	MOV AH, 09H ;DISPLAY INPUT PROMPT
	INT 21H

	LEA DX, STRING
	MOV AH, 0AH ;GET USER INPUT
	INT 21H

	MOV AL, 0
	MOV BH, 1EH 	;BG:FG COLOR
	MOV CH, 2	;FROM ROW
	MOV CL, 10	;FROM COLUMN
	MOV DH, 22	;FROM ROW
	MOV DL, 65	;TO COLUMN
	MOV AH, 06H ;SCROLL A 20X20 WINDOW
	INT 10H

;FOR CURSOR POSITION
	MOV BH, 0
	MOV DH, 12
	MOV DL, 39

	LEA SI, STRING + 2
	MOV CH, 00H
	MOV CL, [STRING+1];LOOP NUMBER

PRINT_LOOP:
	MOV AL, [SI] ;PUT THE CHAR IN AL

	CMP CL, 0 ;LOOP EXIT CONDITIONS
	JE EXIT_DISPLAY
	CMP AL, '$'
	JE EXIT_DISPLAY
	
	MOV AH, 02H ;CHANGE THE CURSOR
	INT 10H

	PUSH CX
	
	MOV BL, 0CH
	MOV CX, 1	;POSSIBLE ERROR CAUSING LINE !!!
	MOV AH, 09H ;PRINT COLORED CHARACTER
	INT 10H
	
	POP CX

	INC SI
	INC DL ;CURSOR POSITION
	DEC CL
	JMP PRINT_LOOP

EXIT_DISPLAY:
	MOV AH, 4CH
	INT 21H
END START
